# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users = User.create([


	{ password: "1234567890", email: "pepe@correo.com", username: "pepe", encrypted_password: "887776665", reset_password_token: "88990022", sign_in_count: 0, current_sign_in_ip: "asdfghjkkl", last_sign_in_ip: "lorem"},
	{ password: "1234567890", email: "cheo@correo.com", username: "cheo", encrypted_password: "887776665", reset_password_token: "88990022", sign_in_count: 0, current_sign_in_ip: "asdfghjkkl", last_sign_in_ip: "lorem"}

	])


associateds = Associated.create([
	
	{name: "Samuel", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, illum.", status: 0, user_id: 1},
	{name: "Jhon", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, repellendus.", status: 0, user_id: 1},
	{name: "Jhonathan", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, error.", status: 0, user_id: 1},
	{name: "Romer", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, iusto?", status: 0, user_id: 2},
	{name: "Daniel", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, aliquid.", status: 0, user_id: 2},
	{name: "Emilio", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est, soluta.", status: 0, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, illum.", status: 0, user_id: 2},
	{name: "Mary", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, fugiat.", status: 0, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, accusamus.", status: 0, user_id: 2},
	{name: "Hector", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore, impedit.", status: 0, user_id: 2},
	{name: "Genesis", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, velit!", status: 0, user_id: 2},
	{name: "Abraham", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, earum.", status: 0, user_id: 2},
	{name: "Pedro", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, illum.", status: 0, user_id: 1},
	{name: "Pablo", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, repellendus.", status: 0, user_id: 1},
	{name: "Mateo", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, error.", status: 0, user_id: 1},
	{name: "Juan", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, iusto?", status: 0, user_id: 2},
	{name: "Daniel", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, aliquid.", status: 0, user_id: 2},
	{name: "Emilio", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est, soluta.", status: 1, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, illum.", status: 1, user_id: 2},
	{name: "Mary", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, fugiat.", status: 1, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, accusamus.", status: 1, user_id: 2},
	{name: "Hector", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore, impedit.", status: 1, user_id: 2},
	{name: "Genesis", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, velit!", status: 1, user_id: 2},
	{name: "Abraham", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, earum.", status: 1, user_id: 2},
	{name: "Moises", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, illum.", status: 1, user_id: 1},
	{name: "Josué", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, repellendus.", status: 1, user_id: 1},
	{name: "David", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, error.", status: 1, user_id: 1},
	{name: "Romer", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, iusto?", status: 1, user_id: 2},
	{name: "Daniel", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, aliquid.", status: 1, user_id: 2},
	{name: "Emilio", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est, soluta.", status: 1, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, illum.", status: 1, user_id: 2},
	{name: "Mary", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, fugiat.", status: 1, user_id: 2},
	{name: "Maria", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, accusamus.", status: 1, user_id: 2},
	{name: "Hector", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 1, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore, impedit.", status: 1, user_id: 2},
	{name: "Genesis", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 0, frequency: 0, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, velit!", status: 1, user_id: 2},
	{name: "Abraham", ci_rif: "23456789", alias: "lorem", email: "lorem@correo.com", phone: "02121234567", address: "Lorem ipsum dolor sit amet", kind: 2, frequency: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, earum.", status: 1, user_id: 2}
	])

products = Product.create([
	{name: "Hack_Full", description: "Curso intensivo de 16 semanas de formación para  programadores", price: 36000.0, user_id: 1},
	{name: "Hack_Part", description: "Curso intensivo de 16 semanas de formación para programadores", price: 10000.0, user_id: 2}
	])

invoices = Invoice.create([
	{kind_operation: 1, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 1, user_id: 1, product_id: 1, name_product: "Hack_Full", name_associated: "Pedro ipsum.", ci_associated: "12345678.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 1, kind_payment: 1, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 2, user_id: 1, product_id: 1, name_product: "Hack_Full", name_associated: "Manuel ipsum.", ci_associated: "987654321.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 3, user_id: 1, product_id: 1, name_product: "Hack_Full", name_associated: "Jose ipsum.", ci_associated: "432123456.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 1, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 4, user_id: 1, product_id: 1, name_product: "Hack_Full", name_associated: "Marco ipsum.", ci_associated: "5678987654.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 5, user_id: 1, product_id: 1, name_product: "Hack_Full", name_associated: "Luis ipsum.", ci_associated: "234565432.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 1, kind_payment: 1, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 6, user_id: 1, product_id: 2, name_product: "Hack_Part", name_associated: "Moises ipsum.", ci_associated: "98767876.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 1, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 7, user_id: 2, product_id: 2, name_product: "Hack_Part", name_associated: "Abraham ipsum.", ci_associated: "3456545.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 1, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 8, user_id: 2, product_id: 2, name_product: "Hack_Part", name_associated: "Sara ipsum.", ci_associated: "234565432.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 1, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 9, user_id: 2, product_id: 2, name_product: "Hack_Part", name_associated: "Ana ipsum.", ci_associated: "7656654322.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 0, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 1, user_id: 2, product_id: 2, name_product: "Hack_Part", name_associated: "Mara ipsum.", ci_associated: "3456445.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."},
	{kind_operation: 0, kind_payment: 1, kind_invoice: 0, description: "Lorem ipsum dolor sit amet At, architecto.", quantity: 1, subtotal: 1000.0, tax: 120.0, total: 1120.0, balance: 0.0, date: "2015-06-10", document: "pdf", payment_proof: "pdf", associated_id: 2, user_id: 2, product_id: 2, name_product: "Hack_Part", name_associated: "Isabel ipsum.", ci_associated: "2345654.", address_associated: "Lorem ipsum dolor sit amet, consectetur adipisicing elit."}
	])

